### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by MalvadoEZY**

### CODE REVIEW

**Comment by SladeGit** [comment]
Pls Help,

On Server start:
(node:9708) ExperimentalWarning: The Node.js specifier resolution in ESM is
experimental.
    at defaultGetFormat (internal/modules/esm/get_format.js:69:17)
    at getFormat (embedder_main_0.js:26:16)
    at Loader.getFormat (internal/modules/esm/loader.js:102:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:231:31)
    at async ModuleWrap.<anonymous>
(internal/modules/esm/module_job.js:58:21)
    at async Promise.all (index 2)
    at async link (internal/modules/esm/module_job.js:63:9)

On finished the Character creation:
(node:9708) UnhandledPromiseRejectionWarning: TypeError: Cannot assign to
read only property 'socialID' of object '#<Player>'
    at Player.LoadCharacter
(file:///C:/Users/Slade/Desktop/newProjekt/resources/core/server/extends/player.mjs:59:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async playerSession
(file:///C:/Users/Slade/Desktop/newProjekt/resources/core/server/player/playerSession.mjs:16:22)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:9708) TypeError: Cannot assign to read only property 'socialID' of
object '#<Player>'
    at Player.LoadCharacter
(file:///C:/Users/Slade/Desktop/newProjekt/resources/core/server/extends/player.mjs:59:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async playerSession
(file:///C:/Users/Slade/Desktop/newProjekt/resources/core/server/player/playerSession.mjs:16:22)
(node:9708) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

On Spawning:
(node:17460) UnhandledPromiseRejectionWarning: TypeError: Cannot read
property 'inventory' of undefined
    at
file:///C:/Users/Slade/Desktop/newProjekt/resources/core/server/extends/inventory.mjs:10:50
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:17460) TypeError: Cannot read property 'inventory' of undefined
    at
file:///C:/Users/Slade/Desktop/newProjekt/resources/core/server/extends/inventory.mjs:10:50
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:17460) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)


Am Sa., 17. Apr. 2021 um 04:31 Uhr schrieb Roberto Alves <
***@***.***>:

**Comment by MalvadoEZY** [comment]
The framework doesn't have the inventory complete and that error is known.
About the socialID make sure you have the rockstar launcher opened because that socialID will come from the social club identifier.

Be aware that the framework just have the simplest roleplay core. Nothing to big

**Comment by SladeGit** [comment]
So the Rockstar Launcher is open but then I get this error and stuck on the black screen :I

**Comment by MalvadoEZY** [comment]
@SladeGit sorry, i will investigate that problem.

**Comment by SwathingBlock** [comment]
Rip

**Comment by SladeGit** [comment]
Note: Nothing works with Dev branch

**Pull request merged**
